name: .NET Deploy Nuget

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ConnectionString: ${{ secrets.CONNECTIONSTRING }}
      Database: "nuages_identity_tests"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Set VERSION variable from tag
      run: |
        echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        echo ${VERSION}
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c RELEASE
    # - name: Test
    #  run: dotnet test Nuages.AspNetIdentity.Stores.Mongo.Tests/Nuages.AspNetIdentity.Stores.Mongo.Tests.csproj -c RELEASE
    - name: Pack
      run: |
        dotnet pack Nuages.AspNetIdentity.Stores/Nuages.AspNetIdentity.Stores.csproj --output ./nupkgs -p:PackageVersion=${VERSION} -c RELEASE
        dotnet pack Nuages.AspNetIdentity.Stores.Mongo/Nuages.AspNetIdentity.Stores.Mongo.csproj --output ./nupkgs -p:PackageVersion=${VERSION} -c RELEASE
    - name: Push
      run: dotnet nuget push ./nupkgs/*.nupkg -k ${{ secrets.NUGETKEY }} -s nuget.org
